//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################

import Testing
@testable import Configuration
import ConfigurationTestingInternal

struct ConfigReaderMethodTestsFetch3 {

    typealias Defaults = ConfigReaderTests.Defaults
    typealias TestEnum = ConfigReaderTests.TestEnum
    typealias TestStringConvertible = ConfigReaderTests.TestStringConvertible

    @available(Configuration 1.0, *)
    @Test func fetch() async throws {
        let config = ConfigReaderTests.config

        do {
            // Optional - success
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["stringConvertibleArray"]),
                    as: TestStringConvertible.self
                ) == Defaults.stringConvertibleArray
            )
            #expect(
                try await config.fetchStringArray(forKey: "stringConvertibleArray", as: TestStringConvertible.self)
                    == Defaults.stringConvertibleArray
            )

            // Optional - missing
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["absentStringConvertibleArray"]),
                    as: TestStringConvertible.self
                ) == nil
            )
            #expect(
                try await config.fetchStringArray(
                    forKey: "absentStringConvertibleArray",
                    as: TestStringConvertible.self
                ) == nil
            )

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(forKey: ConfigKey(["failure"]), as: TestStringConvertible.self)
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(forKey: "failure", as: TestStringConvertible.self)
            }

            // Defaulted - success
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["stringConvertibleArray"]),
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                ) == Defaults.stringConvertibleArray
            )
            #expect(
                try await config.fetchStringArray(
                    forKey: "stringConvertibleArray",
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                ) == Defaults.stringConvertibleArray
            )

            // Defaulted - missing
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["absentStringConvertibleArray"]),
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                ) == Defaults.otherStringConvertibleArray
            )
            #expect(
                try await config.fetchStringArray(
                    forKey: "absentStringConvertibleArray",
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                ) == Defaults.otherStringConvertibleArray
            )

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(
                    forKey: ConfigKey(["failure"]),
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                )
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(
                    forKey: "failure",
                    as: TestStringConvertible.self,
                    default: Defaults.otherStringConvertibleArray
                )
            }

            // Required - success
            #expect(
                try await config.fetchRequiredStringArray(
                    forKey: ConfigKey(["stringConvertibleArray"]),
                    as: TestStringConvertible.self
                ) == Defaults.stringConvertibleArray
            )
            #expect(
                try await config.fetchRequiredStringArray(
                    forKey: "stringConvertibleArray",
                    as: TestStringConvertible.self
                ) == Defaults.stringConvertibleArray
            )

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) {
                try await config.fetchRequiredStringArray(
                    forKey: ConfigKey(["absentStringConvertibleArray"]),
                    as: TestStringConvertible.self
                )
            }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringConvertibleArray"])))
            let error2 = await #expect(throws: ConfigError.self) {
                try await config.fetchRequiredStringArray(
                    forKey: "absentStringConvertibleArray",
                    as: TestStringConvertible.self
                )
            }
            #expect(error2 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringConvertibleArray"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchRequiredStringArray(
                    forKey: ConfigKey(["failure"]),
                    as: TestStringConvertible.self
                )
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchRequiredStringArray(forKey: "failure", as: TestStringConvertible.self)
            }
        }
        do {
            // Optional - success
            #expect(
                try await config.fetchStringArray(forKey: ConfigKey(["stringEnumArray"]), as: TestEnum.self)
                    == Defaults.stringEnumArray
            )
            #expect(
                try await config.fetchStringArray(forKey: "stringEnumArray", as: TestEnum.self)
                    == Defaults.stringEnumArray
            )

            // Optional - missing
            #expect(
                try await config.fetchStringArray(forKey: ConfigKey(["absentStringEnumArray"]), as: TestEnum.self)
                    == nil
            )
            #expect(try await config.fetchStringArray(forKey: "absentStringEnumArray", as: TestEnum.self) == nil)

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(forKey: ConfigKey(["failure"]), as: TestEnum.self)
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(forKey: "failure", as: TestEnum.self)
            }

            // Defaulted - success
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["stringEnumArray"]),
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                ) == Defaults.stringEnumArray
            )
            #expect(
                try await config.fetchStringArray(
                    forKey: "stringEnumArray",
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                ) == Defaults.stringEnumArray
            )

            // Defaulted - missing
            #expect(
                try await config.fetchStringArray(
                    forKey: ConfigKey(["absentStringEnumArray"]),
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                ) == Defaults.otherStringEnumArray
            )
            #expect(
                try await config.fetchStringArray(
                    forKey: "absentStringEnumArray",
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                ) == Defaults.otherStringEnumArray
            )

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(
                    forKey: ConfigKey(["failure"]),
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                )
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchStringArray(
                    forKey: "failure",
                    as: TestEnum.self,
                    default: Defaults.otherStringEnumArray
                )
            }

            // Required - success
            #expect(
                try await config.fetchRequiredStringArray(forKey: ConfigKey(["stringEnumArray"]), as: TestEnum.self)
                    == Defaults.stringEnumArray
            )
            #expect(
                try await config.fetchRequiredStringArray(forKey: "stringEnumArray", as: TestEnum.self)
                    == Defaults.stringEnumArray
            )

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) {
                try await config.fetchRequiredStringArray(
                    forKey: ConfigKey(["absentStringEnumArray"]),
                    as: TestEnum.self
                )
            }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringEnumArray"])))
            let error2 = await #expect(throws: ConfigError.self) {
                try await config.fetchRequiredStringArray(forKey: "absentStringEnumArray", as: TestEnum.self)
            }
            #expect(error2 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringEnumArray"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchRequiredStringArray(forKey: ConfigKey(["failure"]), as: TestEnum.self)
            }
            await #expect(throws: TestProvider.TestError.self) {
                try await config.fetchRequiredStringArray(forKey: "failure", as: TestEnum.self)
            }
        }
    }
}
