
def autogenerated_warning():
    return """\
// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################
"""


primitive_types = [
    {"name": "String", "lowercase_name": "string", "type": "String", "example_default": "\"localhost\""},
    {"name": "Int", "lowercase_name": "int", "type": "Int", "example_default": "3"},
    {"name": "Double", "lowercase_name": "double", "type": "Double", "example_default": "3.14"},
    {"name": "Bool", "lowercase_name": "bool", "type": "Bool", "example_default": "true"},
    {"name": "Bytes", "lowercase_name": "bytes", "type": "[UInt8]", "example_default": "[0x01, 0x02]"},
    {"name": "StringArray", "lowercase_name": "stringArray", "type": "[String]", "example_default": "[\"a\", \"b\"]"},
    {"name": "IntArray", "lowercase_name": "intArray", "type": "[Int]", "example_default": "[1, 2]"},
    {"name": "DoubleArray", "lowercase_name": "doubleArray", "type": "[Double]", "example_default": "[1.0, 2.0]"},
    {"name": "BoolArray", "lowercase_name": "boolArray", "type": "[Bool]", "example_default": "[true, false]"},
    {"name": "ByteChunkArray", "lowercase_name": "byteChunkArray", "type": "[[UInt8]]", "example_default": "[[0x01], [0x02]]"},
]


def lower_first(s):
    return s[:1].lower() + s[1:]


string_convertible_types = [
    {
        "protocol": "ExpressibleByConfigString",
        "testType": "TestStringConvertible",
        "testSuffix": "StringConvertible"
    },
    {
        "protocol": "RawRepresentable<String>",
        "testType": "TestEnum",
        "testSuffix": "StringEnum"
    },
]

int_convertible_types = [
    {
        "protocol": "ExpressibleByConfigInt",
        "testType": "TestIntConvertible",
        "testSuffix": "IntConvertible"
    },
    {
        "protocol": "RawRepresentable<Int>",
        "testType": "TestIntEnum",
        "testSuffix": "IntEnum"
    },
]
