
def autogenerated_warning():
    return """
    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    """


primitive_types = [
    {"name": "String", "lowercase_name": "string", "type": "String",
      "default_example": '"hello"'},
    {"name": "Int", "lowercase_name": "int", "type": "Int",
      "default_example": "3"},
    {"name": "Double", "lowercase_name": "double", "type": "Double",
      "default_example": "1.0"},
    {"name": "Bool", "lowercase_name": "bool", "type": "Bool",
      "default_example": "true"},
    {"name": "Bytes", "lowercase_name": "bytes", "type": "[UInt8]",
      "default_example": "[]"},
    {"name": "StringArray", "lowercase_name": "stringArray", "type": "[String]",
      "default_example": '["hello", "world"]'},
    {"name": "IntArray", "lowercase_name": "intArray", "type": "[Int]",
      "default_example": "[1, 2, 3]"},
    {"name": "DoubleArray", "lowercase_name": "doubleArray", "type": "[Double]",
      "default_example": "[1.0, 2.0, 3.0]"},
    {"name": "BoolArray", "lowercase_name": "boolArray", "type": "[Bool]",
      "default_example": "[true, false]"},
    {"name": "ByteChunkArray", "lowercase_name": "byteChunkArray", "type": "[[UInt8]]",
      "default_example": "[[1, 2], [3, 4]]"},
]


def lower_first(s):
    return s[:1].lower() + s[1:]


string_convertible_types = [
    {
        "protocol": "ExpressibleByConfigString",
        "testType": "TestStringConvertible",
        "testSuffix": "StringConvertible"
    },
    {
        "protocol": "RawRepresentable<String>",
        "testType": "TestEnum",
        "testSuffix": "StringEnum"
    },
]

int_convertible_types = [
    {
        "protocol": "ExpressibleByConfigInt",
        "testType": "TestIntConvertible",
        "testSuffix": "IntConvertible"
    },
    {
        "protocol": "RawRepresentable<Int>",
        "testType": "TestIntEnum",
        "testSuffix": "IntEnum"
    },
]
